from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


FASTA_EXTENSIONS = {".fasta", ".fa", ".fna", ".fas"}


def main() -> None:
    parser = argparse.ArgumentParser(description="Web job runners for Rational Primer Design")
    subparsers = parser.add_subparsers(dest="command")

    for command in ("validate_online", "local_multiplex", "auto_multiplex"):
        cmd = subparsers.add_parser(command)
        cmd.add_argument("--request", required=True, help="Path to a JSON request generated by the API")

    args = parser.parse_args()
    if args.command == "validate_online":
        run_validate_online(_read_json(Path(args.request)))
    elif args.command == "local_multiplex":
        run_local_multiplex(_read_json(Path(args.request)))
    elif args.command == "auto_multiplex":
        run_auto_multiplex(_read_json(Path(args.request)))
    else:
        parser.print_help()
        raise SystemExit(2)


def run_validate_online(request: dict[str, Any]) -> None:
    from .fetcher import SequenceFetcher

    output_dir = Path(request["output_dir"])
    output_dir.mkdir(parents=True, exist_ok=True)
    target_dir = output_dir / "0_raw_data" / "target"
    background_dir = output_dir / "0_raw_data" / "background"
    target_dir.mkdir(parents=True, exist_ok=True)
    background_dir.mkdir(parents=True, exist_ok=True)

    fetcher = SequenceFetcher(request["email"])
    print("[web-job] Fetching target genomes for primer validation...")
    fetcher.fetch_and_save_all(_query_config(request.get("targets", []), "t"), str(target_dir))
    print("[web-job] Fetching background genomes for primer validation...")
    fetcher.fetch_and_save_all(_query_config(request.get("backgrounds", []), "b"), str(background_dir))

    _run_command(
        _validate_command(
            primers_path=Path(request["primers_path"]),
            target_dir=target_dir,
            background_dir=background_dir,
            output_csv=output_dir / "PCR_Advanced_Report.csv",
            extract_sequence=bool(request.get("extract_sequence", False)),
            max_mismatch=int(request.get("max_mismatch", 4)),
            workers=int(request.get("workers", 0)),
            max_len=int(request.get("max_len", 1500)),
        )
    )


def run_local_multiplex(request: dict[str, Any]) -> None:
    target_paths = [Path(item).expanduser().resolve() for item in request.get("target_paths", [])]
    background_path = Path(str(request.get("background_path", ""))).expanduser().resolve()
    _run_multiplex_from_local_sources(
        output_dir=Path(request["output_dir"]),
        target_sources=target_paths,
        shared_background=background_path,
        params_path=Path(request["params_path"]),
        language=str(request.get("language", "vi")),
        assay_type=str(request.get("assay_type", "qPCR")),
        ai_base_url=request.get("ai_base_url"),
        ai_model=request.get("ai_model"),
    )


def run_auto_multiplex(request: dict[str, Any]) -> None:
    from .fetcher import SequenceFetcher

    output_dir = Path(request["output_dir"])
    raw_dir = output_dir / "0_raw_data"
    shared_bg = raw_dir / "shared_bg"
    shared_bg.mkdir(parents=True, exist_ok=True)

    fetcher = SequenceFetcher(request["email"])
    backgrounds = _query_config(request.get("backgrounds", []), "b")
    if backgrounds:
        print(f"[web-job] Fetching {len(backgrounds)} shared background group(s)...")
        fetcher.fetch_and_save_all(backgrounds, str(shared_bg))

    target_sources: list[Path] = []
    for index, target in enumerate(request.get("targets", []), start=1):
        target_dir = raw_dir / f"t{index}"
        target_dir.mkdir(parents=True, exist_ok=True)
        print(f"[web-job] Fetching multiplex target #{index}: {target.get('query', '')}")
        fetcher.fetch_and_save_all(_query_config([target], "t"), str(target_dir))
        target_sources.append(target_dir)

    _run_multiplex_from_local_sources(
        output_dir=output_dir,
        target_sources=target_sources,
        shared_background=shared_bg,
        params_path=Path(request["params_path"]),
        language=str(request.get("language", "vi")),
        assay_type=str(request.get("assay_type", "qPCR")),
        ai_base_url=request.get("ai_base_url"),
        ai_model=request.get("ai_model"),
        target_names=[str(item.get("query", f"Target {idx}")) for idx, item in enumerate(request.get("targets", []), start=1)],
    )


def _run_multiplex_from_local_sources(
    *,
    output_dir: Path,
    target_sources: list[Path],
    shared_background: Path,
    params_path: Path,
    language: str,
    assay_type: str,
    ai_base_url: str | None,
    ai_model: str | None,
    target_names: list[str] | None = None,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    shared_context = output_dir / "shared_primer_context.json"
    target_folders: list[Path] = []

    for index, target_source in enumerate(target_sources, start=1):
        target_folder = output_dir / f"t{index}"
        target_folder.mkdir(parents=True, exist_ok=True)
        target_folders.append(target_folder)

        target_name = target_names[index - 1] if target_names and index - 1 < len(target_names) else target_source.name
        _write_json(target_folder / "metadata.json", {"target_name": target_name})

        virtual_bg = output_dir / "0_raw_data" / f"bg_for_t{index}"
        virtual_bg.mkdir(parents=True, exist_ok=True)
        if shared_background.exists():
            _copy_sequence_files(shared_background, virtual_bg)

        for other_index, other_source in enumerate(target_sources, start=1):
            if other_index == index:
                continue
            _copy_sequence_files(other_source, virtual_bg, prefix=f"target_bg_t{other_index}_")

        command = [
            sys.executable,
            "-m",
            "rational_design.cli",
            "pipeline",
            "--out",
            str(target_folder),
            "--local_target",
            str(target_source),
            "--local_bg",
            str(virtual_bg),
            "--params",
            str(params_path),
            "--language",
            language if language in {"vi", "en"} else "vi",
            "--shared_context",
            str(shared_context),
        ]
        if ai_base_url:
            command.extend(["--ai_base_url", str(ai_base_url)])
        if ai_model:
            command.extend(["--ai_model", str(ai_model)])
        _run_command(command)

    command = [
        sys.executable,
        "-m",
        "rational_design.cli",
        "multiplex_analyze",
        "--folders",
        *[str(folder) for folder in target_folders],
        "--out",
        str(output_dir),
        "--language",
        language if language in {"vi", "en"} else "vi",
        "--assay_type",
        assay_type if assay_type in {"qPCR", "Conventional"} else "qPCR",
    ]
    if ai_base_url:
        command.extend(["--ai_base_url", str(ai_base_url)])
    if ai_model:
        command.extend(["--ai_model", str(ai_model)])
    _run_command(command)


def _validate_command(
    *,
    primers_path: Path,
    target_dir: Path,
    background_dir: Path,
    output_csv: Path,
    extract_sequence: bool,
    max_mismatch: int,
    workers: int,
    max_len: int,
) -> list[str]:
    command = [
        sys.executable,
        "-m",
        "rational_design.cli",
        "validate_primers",
        "-c",
        str(primers_path),
        "-t",
        str(target_dir),
        "-b",
        str(background_dir),
        "-o",
        str(output_csv),
        "-e",
        str(max_mismatch),
        "-w",
        str(workers),
        "--max_len",
        str(max_len),
    ]
    if extract_sequence:
        command.append("-s")
    return command


def _copy_sequence_files(source: Path, destination: Path, prefix: str = "") -> None:
    if source.is_file() and source.suffix.lower() in FASTA_EXTENSIONS:
        shutil.copy2(source, destination / f"{prefix}{source.name}")
        return
    if not source.is_dir():
        return
    for path in source.iterdir():
        if path.is_file() and path.suffix.lower() in FASTA_EXTENSIONS:
            shutil.copy2(path, destination / f"{prefix}{path.name}")


def _query_config(items: list[dict[str, Any]], prefix: str) -> dict[str, list[Any]]:
    config = {}
    for index, item in enumerate(items, start=1):
        query = str(item.get("query", "")).strip()
        if not query:
            continue
        config[f"{prefix}{index}"] = [
            query,
            float(item.get("size", 0.0) or 0.0),
            int(item.get("count", 0) or 0),
            str(item.get("type", "genome") or "genome"),
        ]
    return config


def _run_command(command: list[str]) -> None:
    print("[web-job] Running:", " ".join(command), flush=True)
    completed = subprocess.run(command, text=True)
    if completed.returncode != 0:
        raise SystemExit(completed.returncode)


def _read_json(path: Path) -> dict[str, Any]:
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(data, handle, ensure_ascii=False, indent=2)


if __name__ == "__main__":
    main()
